# Generated by Django 3.2 on 2024-01-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='qr_image',
        ),
        migrations.AddField(
            model_name='booking',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='booking_barcode_images/'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
