# Generated by Django 3.2 on 2024-01-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20240128_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='barcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
