# Generated by Django 3.2 on 2024-01-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='barcode',
            field=models.CharField(default='', max_length=13),
        ),
    ]
