# Generated by Django 3.2 on 2024-01-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_barcode_expired',
            field=models.BooleanField(default='False'),
        ),
    ]
