# Generated by Django 3.2 on 2024-01-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='issued_ticket_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
