# Generated by Django 3.2 on 2024-01-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20240120_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booked_ticket_quantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
