# Generated by Django 3.2 on 2024-01-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_booked_ticket_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='issued_ticket_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
