# Generated by Django 3.2 on 2024-02-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='commision_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
